export const ErrorCodes = {
    GET_NOTE_NOT_FOUND: 'GET_NOTE_NOT_FOUND',
    GET_NOTE_FAILURE: 'GET_NOTE_FAILURE',

    UPDATE_NOTE_FAILURE: 'UPDATE_NOTE_FAILURE',

    CREATE_NOTE_FAILURE: 'CREATE_NOTE_FAILURE',
}
